name: Production Catalog Sync

on: 
    # schedule:
    #    - cron: '30 5,17 * * *'
    workflow_dispatch:

jobs:
  update-all-records-staging:

    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Update all records
        run: |
          python src/main.py
        env:
          BR_SHOPIFY_URL: ${{ vars.BR_SHOPIFY_URL }}
          BR_SHOPIFY_PAT: ${{ secrets.BR_SHOPIFY_PAT }}
          BR_ENVIRONMENT_NAME: ${{ vars.BR_ENVIRONMENT_NAME }}
          BR_ACCOUNT_ID: ${{ vars.BR_ACCOUNT_ID }}
          BR_CATALOG_NAME: ${{ vars.BR_CATALOG_NAME }}
          BR_API_TOKEN: ${{ secrets.BR_API_TOKEN }}
          BR_OUTPUT_DIR: "."
